### ISSUE TITLE
compact declaration support?

### ISSUE THREAD

**Issue by lifeart** [jelhan/ember-style-modifier#1]
Is it possible to have compact declaration, like 

```hbs
<p {{style border="1px" padding="1em !important"}} />
```

**Comment by jelhan** [comment]
I like that syntax! :+1: It not only reduces verbosity if setting more than one CSS property but also fixes the issue of dynamic property names.

**Comment by lifeart** [comment]
don't think it can help with dynamic property names (it can't be mutable). but
I think it can be an API for it, like

```hbs
<p {{style this.styleHash}}></p>
```
```js
this.styleHash = { fontFamily: monospace; fontSize: 12em } 
```

**Comment by jelhan** [comment]
I'm tending to not support dynamic property names at all. I don't see a use case in which you have an unlimited number of potential properties to address. If it's just about not setting a specific property for a specific scenario passing `undefined` or an empty string should be fine.

**Comment by jelhan** [comment]
Reopening as @buschtoens also requested the ability to pass a hash with styles. So there seems to be a need. But need to figure out how we could support this including `rollback` / `teardown` mechanism if a property is not present anymore on hash after update.
