### ISSUE TITLE
breaks ember-basic-dropdown

### ISSUE THREAD

**Issue by jeffstagedoor** [jelhan/ember-style-modifier#123]
It seems that installing this component breaks the following other components, which depend on ember-basic-dropdown:
- ember-power-select
- ember-power-calendar

This for sure could be an issue of ember-basic-dropdown and I'll leave an issue there too.

**Comment by jelhan** [comment]
Please provide some additional details.

How is it breaking? Is it a build-time error? A run-time error? Is an error logged? Do you habe a stack trace?

Also it would be helpful if you could provide versions for the following packages.

- ember-style-modifier
- ember-power-select
- ember-power-calendar
- ember-modifiers
- ember-source

Some of them may be indirect dependency. You could use `yarn why <package>` to find out there exact version.

**Comment by jeffstagedoor** [comment]
I'm sorry for not providing enough (or any) information in first place, very rude from me, I appologize.

There are not any errors shown, neighter in build, nor in using. The mentioned addons simple seem to not do anything anymore. (uninstalling ember-style-modifier made it all work again)

Here are the versions I'm using atm:
ember-modifier: 3.2.7
ember-power-calendar: 0.18.0
ember-power-select: 6.0.1
ember-basic-dropdown: 6.0.0
ember-source: 3.26.1

**Comment by jeffstagedoor** [comment]
the maintainer of ember-basic-dropdown answered me with a probable solution:
https://github.com/cibernox/ember-power-select/issues/1554#issuecomment-1312253581

**Comment by jelhan** [comment]
@jeffstagedoor Did `ember-basic-dropdown@6.0.2` fixed the issue?

**Comment by jelhan** [comment]
Closing due to missing feedback.
