### ISSUE TITLE
peseudoselectors support

### ISSUE THREAD

**Issue by lifeart** [jelhan/ember-style-modifier#2]
It will be great to have `:before`, `:after` pseudoselectors support for usecases like

```hbs
<div {{style ":before" content=this.someText}} />
```

**Comment by jelhan** [comment]
As far as I know pseudoselectors aren't supported by inline styles nor CSSOM. This addons tries to be a replacement for `<div style="border: 1px"></div>` at first place. It aims to provide a nice API that doesn't violate Content Security Policy.

Having that said, it should be possible by inserting a CSS rule in an existing stylesheet ([`CSSStyleSheet.insertRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule)) but that would add a lot of complexity as it requires an existing style sheet that could be modified and some logic to ensure that these CSS rule only matches this one element.

Considering it as out of scope for now but keeping the issue open. If someone is willing to invest time on it, please ping me on discord.

**Comment by lifeart** [comment]
I think it can be implemented in little bit `rude` form with manual style node creation

```js
    const css = `[data-some-node-id=some-uid-for-node]:active { some-serialized-values: 12}`;
    const style = document.createElement("style");
    const head = document.head;
    style.type = "text/css";
    if (style.styleSheet) {
      style.styleSheet.cssText = css;
    } else {
      style.appendChild(document.createTextNode(css));
    }

    head.appendChild(style);
```

and we can keep style node to update it in case of data change

**Comment by jelhan** [comment]
This would require a Content Security Policy `style-src-elem: "unsafe-inline"`. My main motivation for this addon was providing a way to attach custom styles to elements without violating a strict CSP.

**Comment by jelhan** [comment]
Requirements here are very similar to the ones need for SSR/Fastboot support. Please have a look in #11 for details. I guess we could land pseudoselector support soon after landing SSR/Fastboot support.

**Comment by jelhan** [comment]
Coming back to this after quite some while, I'm wondering what the actual use case is. Why would you use CSS pseudoselectors `:before` and `:after` to insert an element, if already being in template scope?
