### ISSUE TITLE
Convert addon to v2 & allow older ember-source versions than 4.12

### ISSUE THREAD

**Issue by mkszepp** [jelhan/ember-style-modifier#217]
While updating `ember-basic-dropdown` to a V2 addon, i have seen that this addon is atm a V1 addon.
I would like that `ember-basic-dropdown` brings early / later all dependencies as addon V2 (better earlier 😅).

Is there planned to port this addon to V2? I think that its very easy for this addon, because the addon is very lite.
The requirement for V2 addon is `ember-auto-import` v2 or embroider (see [Addon V2 RFCS](https://rfcs.emberjs.com/id/0507-embroider-v2-package-format/))

The other idea is to allow also older `ember-source` (atm v4.12+ is required). This means that only latest 2 LTS versions are supported. I don't understand why this is necessary... Is there any reason?
All dependency packages are allowing at least v3.28+... so would be great that we can also support this addon for older ember apps.

If you need any help to convert to V2 please let me know.

**Comment by jelhan** [comment]
> While updating `ember-basic-dropdown` to a V2 addon, i have seen that this addon is atm a V1 addon. I would like that `ember-basic-dropdown` brings early / later all dependencies as addon V2 (better earlier 😅).
> 
> Is there planned to port this addon to V2? I think that its very easy for this addon, because the addon is very lite. The requirement for V2 addon is `ember-auto-import` v2 or embroider (see [Addon V2 RFCS](https://rfcs.emberjs.com/id/0507-embroider-v2-package-format/))
>
> [...]
>
> If you need any help to convert to V2 please let me know.

As all Ember addons it should be converted to a v2 addon. Main blocker is limited OSS time from my side. A PR doing the migration is very welcome.

`ember-auto-import@v2` is already a dependency. So it should not require any breaking changes.

> The other idea is to allow also older `ember-source` (atm v4.12+ is required). This means that only latest 2 LTS versions are supported. I don't understand why this is necessary... Is there any reason?
> All dependency packages are allowing at least v3.28+... so would be great that we can also support this addon for older ember apps.

You are right. There aren't any technical reasons for dropping support for Ember < 4.12. Primary reasons to drop support for Ember versions, which reached end of life is easing maintenance. This is also motivated by my limited OSS time.

Addons, which want to support older Ember versions can do so by allowing multiple versions of `ember-style-modifier` themselves. This is also recommended to avoid dependency hell.

I'm open to widen the supported Ember versions again, if you (or others) commit to help with maintaining them over time.

**Comment by mkszepp** [comment]
@jelhan okay thanks for info... when i get time today or next days, i will make a PR for converting the addon to V2. After/while migration i will try to readd ember try's for older ember versions... If this works without any warnings/errors we hold them.

> Addons, which want to support older Ember versions can do so by allowing multiple versions of ember-style-modifier themselves. This is also recommended to avoid dependency hell.

Yes, thats true, in `ember-basic-dropdown` we have since now alway supported more/less every version of `ember-style-modifier` (0.8.0+ 😅), because there were never braking changes in this addon (+- only dependencies were always). There were always only added but never removed... with next version i will try to support less versions of dependencies as possible. Consumer apps should update there packages always completly or staying on older versions, but should never mix ouddated packages with up-to-date packages, because this brings for us addon maintainer always more work.
