### ISSUE TITLE
can not install v0.6.0 with npm or yarn

### ISSUE THREAD

**Issue by nightire** [jelhan/ember-style-modifier#41]
It's very strange that I can't install `ember-style-modifier@0.6.0` with npm or yarn, but I can see this version appears on the npmjs.com website, how is this possible?

This is what I saw when it failed:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ember-style-modifier@^0.6.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

BTW I've tried `yarn cache clean` or `npm cache clean --force`, doesn't work either.

**Comment by jelhan** [comment]
That sounds very strange indeed. Other projects use `ember-style-modifer@0.6.0` without facing any troubles. E.g. Ember Bootstrap: https://github.com/kaliber5/ember-bootstrap/blob/dd3db0c6889e270e2c83ea8fea9681abfb2d191b/yarn.lock#L6465-L6471

Are you maybe using another NPM registry than the default public NPM registry? Maybe something is broken with the proxy for public packages used by that NPM registry?
