### ISSUE TITLE
Refactor away from ember-functional-modifiers

### ISSUE THREAD

**Issue by buschtoens** [jelhan/ember-style-modifier#7]
https://github.com/jelhan/ember-style-modifier/blob/324445fc768b851f44578c675821356d8b3f92ba/addon/modifiers/style.js#L7-L11

This is a clear indicator that this modifier is in fact not _functional_ / a [pure function](https://en.wikipedia.org/wiki/Pure_function). 😄 

I would suggest to refactor this to not use `ember-functional-modifiers` (even though it's great!) and instead interact with the manager and state bucket directly. I'm doing this in [`ember-on-modifier`](https://github.com/buschtoens/ember-on-modifier/blob/700ce6dd79e5595410e5f397b4c2c95ddedb5727/addon/modifiers/on.js#L37-L82) for instance.

I'd be happy to submit a PR as well, if you like.

**Comment by jelhan** [comment]
:100: Wasn't aware of ember-on-modifier when I started this project and hadn't the time yet to refactor to ember-on-modifier. Getting a PR would be awesome.
