### ISSUE TITLE
ember-modifier v3.2 deprecations

### ISSUE THREAD

**Issue by Windvis** [jelhan/ember-style-modifier#87]
ember-modifier [recently released v3.2](https://github.com/ember-modifier/ember-modifier/releases/tag/v3.2.0) which deprecated a lot of things and it seems this addon is affected by it.

I haven't looked into the specifics yet, but there is a [migration guide](https://github.com/ember-modifier/ember-modifier/blob/master/MIGRATIONS.md#40).

**Comment by boris-petrov** [comment]
Yep, I see `ember-modifier.no-args-property`, `ember-modifier.no-element-property`, `ember-modifier.use-modify` and `ember-modifier.use-destroyables`.

cc @jelhan

**Comment by jelhan** [comment]
Thanks a lot for reporting. I'm not sure how soon I will have the time to address these deprecations. A pull request is highly welcome.

**Comment by jelhan** [comment]
Thanks a lot to @bertdeblock for fixing these deprecation (and some bugs in `ember-modifier` package itself). You shouldn't see this deprecation anymore after upgrading to v0.8.0, which I released just now.
